get_hourly_usage:
  fields:
    date:
      required: true
      example: "2026-06-07"
      selector:
        date:
    config_entry_id:
      required: false
      example: "abc123"
      selector:
        config_entry:
          integration: powershop_nz
